/*
 * Author: Tom Giallanza
 * Course: CSC 460 Database Design
 * Assignment: Program 2
 * Instructor: Dr. McCann
 * TAs: Jianwei Shen and Muhammad Bilal
 * Due Date: 02-12-2026
 *
 * Description:
 * This program generates an index file for a fixed-width binary dataset.
 * It operates on a pre-existing binary file containing bat cave records
 * and builds an auxiliary index structure to support efficient lookup
 * and searching operations.
 *
 * The program performs the following operations when executed:
 * 1. Determines the path to the binary data file from the command-line
 *    arguments or defaults to "Dataset2.bin"
 * 2. Initializes an nndexWriter using the binary file
 * 3. Clears any existing index data
 * 4. Rebuilds the index from the contents of the binary file
 * 5. Writes the finalized index structure to disk
 * 6. Displays index bucket statistics, including:
 *      a) Number of buckets
 *      b) Lowest bucket occupancy
 *      c) Highest bucket occupancy
 *      d) Mean and median bucket occupancy
 *
 * The index file is intended for use by companion programs that require
 * fast access to records stored in the binary dataset without scanning
 * the file sequentially.
 *
 * Operational Requirements:
 *   Language: Java 25.0.1
 *   Compilation: javac Prog21.java
 *   Execution: java Prog21 <Binary File Path>
 *   Input: Fixed-width binary data file (default: Dataset2.bin)
 *   Output: Index file generated by IndexWriter
 */

import java.io.*;
import java.util.*;

class Prog21 {

    /*
     * Determines the file system path of the binary data file.
     *
     * If a command-line argument is provided, it is interpreted as the
     * path to the binary file. Otherwise, the program defaults to using
     * "Dataset2.bin" in the current working directory.
     *
     * @param args Command-line arguments
     * @return File object representing the binary file path
     * @throws IOException if file handling fails
     */
    public static File getBinFilePath(String[] args) throws IOException {
        File binFilePath;   // Stores the OS file path of the binary file

        // If an argument was provided, use it as the binary file's path name
        if (args.length > 0)
            binFilePath = new File(args[0]);
        // Otherwise, default to Dataset2.bin
        else
            binFilePath = new File("Dataset2.bin");

        return binFilePath;
    }
    
    /*
     * Creates and writes an index file for the specified binary data file.
     *
     * This method initializes an IndexWriter object, clears any existing
     * index data, rebuilds the index from the binary file contents, and
     * writes the index to persistent storage.
     *
     * @param binFilePath File object referencing the binary data file
     * @throws IOException if index creation or file access fails
     */
    public static void writeIndexFile(File binFilePath) throws IOException {
        IndexWriter indexWriter = new IndexWriter();

        // Remove any previously stored index data
        indexWriter.clearIndex();

        // Open the binary and index files for reading
        indexWriter.open(binFilePath);

        // Populate the index using records from the binary file
        indexWriter.populateIndex();

        // Write the index structure to disk
        indexWriter.writeHashIter();

        // Display the stats for the buckets
        indexWriter.displayBucketStats();

        // Close the file stream when done
        indexWriter.close();
    }

    /*
     * Program entry point.
     *
     * Retrieves the binary file path, then generates an index file
     * based on the contents of the binary dataset. Any I/O errors
     * encountered during execution are reported to the user.
     *
     * @param args Command-line arguments
     */
    public static void main(String[] args) {
        try {
            // Get the binary file path
            File binFilePath = getBinFilePath(args);

            // Write the index file using the binary file
            writeIndexFile(binFilePath);
        } catch (IOException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

}
